---
title: "Step6_Overlap between ActD- and ActD+"
author: "Yeonui+Kwak"
date: "8/16/2020"
output: html_document
---


1.Set a working directory
```{R}
setwd("~/Desktop/Publication_Mar/Final_Fig8/Rcode/step6")

```


#set up color
```{r}
library(RColorBrewer)
library(purrr)
#nstall.packages("raster")
library(raster)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
yk.col = function(n = 5, sat = 0.7, lum = 1) {
	col = c("royalblue4", "deepskyblue3", "turquoise3",
	   "grey62", "goldenrod2", "orange2", "orangered2") %>%
	col2rgb %>%
	rgb2hsv
	return(colorRampPalette(hsv(col[1,], col[2,] * sat,
				    col[3,] * lum))(n)) }

```


```{r}

noactd<-read.table("threshold5,fdr0.2_0.1h.PALchange.txt",header=T,stringsAsFactors = F,sep="\t")
noactd%>%group_by(comparison,change)%>%summarise(n())
actd<-read.table("ActD_PALchange.transcriptid.list.txt",header=T,stringsAsFactors = F,sep="\t")
actd%>%filter(comparison=="0h - 1h")%>%
  filter(change=="UP")%>%
  inner_join(noactd%>%filter(comparison=="0h - 1h")%>%
  filter(change=="UP"),by="hgnc")

```