---
title: "F4S6_customPALdynamics"
author: "Yeonui+Kwak"
date: "6/15/2020"
output: html_document
---

1.Set a working directory
```{R}
setwd("~/Desktop/Publication_Mar/Fig4/Tmp6")

```
2.Load the required packages,and set up colorcode.
```{r}
library(RColorBrewer)
#nstall.packages("raster")
library(raster)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
yk.col = function(n = 5, sat = 0.7, lum = 1) {
	col = c("royalblue4", "deepskyblue3", "turquoise3",
	   "grey62", "goldenrod2", "orange2", "orangered2") %>%
	col2rgb %>%
	rgb2hsv
	return(colorRampPalette(hsv(col[1,], col[2,] * sat,
				    col[3,] * lum))(n)) }
```


```{R}
BiocManager::install("ComplexHeatmap")
library(ComplexHeatmap)
### Heatmap with Annotation
library(dendextend)
library("circlize")
library("RColorBrewer")
library(cluster)    # clustering algorithms
library(factoextra)


yk.col = function(n = 5, sat = 0.7, lum = 1) {
  col = c("royalblue4", "deepskyblue3", "turquoise3",
          "#999999", "goldenrod2", "orangered1", "red") %>%
    col2rgb %>%
    rgb2hsv
  return(colorRampPalette(hsv(col[1,], col[2,] * sat,
                              col[3,] * lum))(n)) }

```

3.Load the PAL file.
```{R}
custom<-read.table("custom.paldynamics.ofpalchanged isoforms(1893).txt",stringsAsFactors = F,header=T)
head(custom)
custom%>%select(hgnc)%>%arrange(hgnc)%>%distinct()%>%nrow()
custom[,2:5]=(custom[,2:5]-apply(custom[,2:5],1,mean))
#custom[,2:5]=(custom[,2:5]-custom[,2])
colnames(custom)=c("newid","0h","1h","2h","4h","hgnc")
```



```{R}
#col<-RColorBrewer::brewer.pal(8,"Paired")
k2 <- kmeans(custom[,2:5], centers=9  , nstart = 25)

highly_Var = as.tibble(custom)%>%
  mutate("cl"=k2$cluster)%>%
  group_by(cl)%>%arrange(cl,desc(`0h`),desc(`1h`),desc(`2h`),desc(`4h`))%>%
  ungroup()%>%mutate(cl=factor(cl,levels=c(1:9)))#%>%mutate(newcl=ifelse(cl==3,1,
                                                                        ifelse(cl==4,2,
                                                                               ifelse(cl==5,3,
                                                                                      ifelse(cl==7,4,
                                                                                             ifelse(cl==1,5,
                                                                                                    ifelse(cl==2,6,                                                                                                           ifelse(cl==6,7,cl))))))))
#TNF
highly_Var%>%filter(grepl("ENST00000449264",newid))
nrow(highly_Var)
write.table(highly_Var,"9cluster.txt",sep="\t",col.names = T,row.names = F,quote = F)
```

```{r}
highly_Var<-read.table("9cluster.txt",stringsAsFactors = F,header=T)
colnames(highly_Var)[2:5]=c(0,1,2,4)
ha = HeatmapAnnotation(df = data.frame(TimeuponLPS= as.factor(c(0,1,2,4))))
pdf("tedseq_1000genes.pdf",height=6,width=4)
Heatmap(highly_Var[,2:5], name = "PAL-meanPAL", 
        show_row_names = F,cluster_columns = F,show_column_names = TRUE,  split=highly_Var$newcl,col= circlize::colorRamp2(seq(-20,20,5), yk.col(9)))
dev.off()


head(highly_Var)
pdf("F1C_tedseq_1000genes_linecol8.pdf",height=8,width=2.5)
highly_Var%>%gather("time","pal",-newcl,-newid,-cl,-hgnc)%>%
  mutate(time=as.numeric(time))%>%group_by(newid)%>%ungroup()%>%ggplot(aes(time,pal,group=newid))+geom_line(aes(col=as.factor(newcl),alpha=0.2))+facet_grid(newcl~.,scales="fixed",switch="both")+ylab("PAL")+
  scale_color_manual(values =yk.col(9),name = "Cluster" )+theme(strip.text = element_text(size=12))+theme(legend.position = "none")+
  theme_bw()
dev.off()
nrow(highly_Var)
```


Enlarge the cluster 5,6,7
```{R}
subset=highly_Var%>%filter(newcl%in%c(5,6,7))
subset=subset%>%arrange(hgnc)%>%group_by(hgnc)%>%mutate(index=row_number())%>%unite("newhgnc",c(hgnc,index),sep=": ")
t=subset[,2:5]
rownames(t)=subset$newhgnc
pdf("cluster5.6.7.pdf",height=15,width=6)
Heatmap(t, name = "PAL-meanPAL", 
        show_row_names = T,cluster_columns = F, show_column_names = TRUE,  split=subset$newcl,col= circlize::colorRamp2(seq(-20,20,5), yk.col(9)))
dev.off()

```


gene list per cluster
```{R}
head(highly_Var)
for (i in 1:9){
  write.table(highly_Var%>%filter(newcl==i)%>%select(newid)%>%separate(newid,c("tid","no"),sep="\\.")%>%select(tid)%>%arrange(tid)%>%distinct(),paste("paldynamics.cl",i,
                                                             ".txt",sep=""),quote = F,col.names = F,row.names = F)
}

#background

bg=read.table("custom.meanPAL.acrossalltimepoints.txt",header=T,stringsAsFactors = F)
write.table(bg%>%select(newid)%>%separate(newid,c("tid","no"),sep="\\.")%>%select(tid)%>%arrange(tid)%>%distinct(),"paldynamics.background.txt",quote = F,col.names = F,row.names = F)
head(bg)
```