---
title: "F6S2"
author: "Yeonui+Kwak"
date: "6/17/2020"
output: html_document
---

1.Set a working directory
```{R}
setwd("~/Desktop/Publication_Mar/Fig6/Tmp2")

```
#set up color
```{r}
library(RColorBrewer)
#nstall.packages("raster")
library(raster)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
yk.col = function(n = 5, sat = 0.7, lum = 1) {
	col = c("royalblue4", "deepskyblue3", "turquoise3",
	   "grey62", "goldenrod2", "orange2", "orangered2") %>%
	col2rgb %>%
	rgb2hsv
	return(colorRampPalette(hsv(col[1,], col[2,] * sat,
				    col[3,] * lum))(n)) }
```


3. Load sample
3.1 PAL-RNA
```{R}
final<-read.table("PRO_TED_CPS.readcounttable.txt",sep="\t",header=T,stringsAsFactors = F)
ted=final[,c(1,5:8)]
colnames(ted)[2:5]=c("t_0", "t_1", "t_2", "t_4")
cps=final[,c(1,10:13)]
colnames(cps)[2:5]=c("t_0", "t_1", "t_2", "t_4")
```



#Correlation heatmap.
```{R}

dcps=cps %>% filter_if(is.numeric, all_vars(. > 0)) %>%
	mutate(d_0_1 = log2(t_1 / t_0),
	       d_0_2 = log2(t_2 / t_0),
	       d_1_2 = log2(t_2 / t_1),
	       d_0_4 = log2(t_4 / t_0),
	       d_1_4 = log2(t_4 / t_1),
	       d_2_4 = log2(t_4 / t_2)) 
dpal=ted %>%
	mutate(d_0_1 = (t_1 - t_0),
	       d_0_2 = (t_2 - t_0),
	       d_1_2 = (t_2 - t_1),
	       d_0_4 = (t_4 - t_0),
	       d_1_4 = (t_4 - t_1),
	       d_2_4 = (t_4 - t_2)) %>%
	select(newid, contains("d"))%>%
	inner_join(dcps, by = "newid")



#%>%right_join(genes.cm, by = "id")
head(dcps)
head(dpal)
```

# Correlation heatmap between pseudo_timecourse of 
```{R}
library(grid)
	yk.col = function(n = 5, sat = 0.7, lum = 1) {
  col = c("royalblue4", "deepskyblue3", "turquoise3",
          "#999999", "goldenrod2", "orangered1", "red") %>%
    col2rgb %>%
    rgb2hsv
  return(colorRampPalette(hsv(col[1,], col[2,] * sat,
                              col[3,] * lum))(n)) }
col = yk.col(121)
br = -60:60/100
#pdf("pdf/FigS3E.pdf", width = 3.2, height = 3)
#x=pal,y=cps
mat = cor(dpal[c(8,9,11,10,12,13)],dpal[c(2,3,5,4,6,7)])
labels = c(expression(0*h %->% 1*h),
	   expression(0*h %->% 2*h),
	   expression(0*h %->% 4*h),
	   expression(1*h %->% 2*h),
	   expression(1*h %->% 4*h),
	   expression(2*h %->% 4*h))
#install.packages("pheatmap")
library(pheatmap)
pdf("heatmap_dPAL_dCPS_alltranscript.pdf", width = 3.2, height = 3)
pheatmap(mat,
	cluster_rows = F,
	cluster_cols = F,
	labels_row = labels,
	labels_col = labels,
	breaks = br,
	color = col,
	main = expression(italic(Delta)*PAL-italic(Delta)*RNA~correlation))
dev.off()


```

2. PRO-PAL
```{R}
final<-read.table("PRO_TED_CPS.readcounttable.txt",sep="\t",header=T,stringsAsFactors = F)
ted=final[,c(1,5:8)]
colnames(ted)[2:5]=c("t_0", "t_1", "t_2", "t_4")
pro=final[,c(1,14:17)]
colnames(pro)[2:5]=c("t_0", "t_1", "t_2", "t_4")
```

```{r}
dpal = ted %>%
	mutate(d_0_1 = (t_1 - t_0),
	       d_0_2 = (t_2 - t_0),
	       d_1_2 = (t_2 - t_1),
	       d_0_4 = (t_4 - t_0),
	       d_1_4 = (t_4 - t_1),
	       d_2_4 = (t_4 - t_2)) %>%
	select(newid, contains("d"))

#%>%right_join(genes.cm, by = "id")
head(dpro)
dpal = pro %>%
	mutate(d_0_1 = (t_1 - t_0),
	       d_0_2 = (t_2 - t_0),
	       d_1_2 = (t_2 - t_1),
	       d_0_4 = (t_4 - t_0),
	       d_1_4 = (t_4 - t_1),
	       d_2_4 = (t_4 - t_2)) %>%
	select(newid, contains("d"))%>%
	inner_join(dpal, by = "newid")

#y=pal;x=pro
mat = cor(dpal[c(8,9,11,10,12,13)],dpal[c(2,3,5,4,6,7)])
labels = c(expression(0*h %->% 1*h),
	   expression(0*h %->% 2*h),
	   expression(0*h %->% 4*h),
	   expression(1*h %->% 2*h),
	   expression(1*h %->% 4*h),
	   expression(2*h %->% 4*h))
#install.packages("pheatmap")
library(pheatmap)
pdf("heatmap_dPRO_dPAL_alltranscript.pdf", width = 3.2, height = 3)
pheatmap(mat,
	cluster_rows = F,
	cluster_cols = F,
	labels_row = labels,
	labels_col = labels,
	breaks = br,
	color = col,
	main = expression(italic(Delta)*PRO-italic(Delta)*PAL~correlation))
dev.off()

```

3. PRO-RNA
```{R}
final<-read.table("PRO_TED_CPS.readcounttable.txt",sep="\t",header=T,stringsAsFactors = F)
cps=final[,c(1,10:13)]
colnames(cps)[2:5]=c("t_0", "t_1", "t_2", "t_4")
pro=final[,c(1,14:17)]
colnames(pro)[2:5]=c("t_0", "t_1", "t_2", "t_4")
```

```{r}

#%>%right_join(genes.cm, by = "id")
dcps = cps %>% filter_if(is.numeric, all_vars(. > 0)) %>%
	mutate(d_0_1 = log2(t_1 / t_0),
	       d_0_2 = log2(t_2 / t_0),
	       d_1_2 = log2(t_2 / t_1),
	       d_0_4 = log2(t_4 / t_0),
	       d_1_4 = log2(t_4 / t_1),
	       d_2_4 = log2(t_4 / t_2)) %>%
	select(newid, contains("d")) 
head(dpro)
dpal = pro %>%
	mutate(d_0_1 = (t_1 - t_0),
	       d_0_2 = (t_2 - t_0),
	       d_1_2 = (t_2 - t_1),
	       d_0_4 = (t_4 - t_0),
	       d_1_4 = (t_4 - t_1),
	       d_2_4 = (t_4 - t_2)) %>%
	select(newid, contains("d"))%>%
	inner_join(dcps, by = "newid")

#y=rna;x=pro
mat = cor(dpal[c(8,9,11,10,12,13)],dpal[c(2,3,5,4,6,7)])
labels = c(expression(0*h %->% 1*h),
	   expression(0*h %->% 2*h),
	   expression(0*h %->% 4*h),
	   expression(1*h %->% 2*h),
	   expression(1*h %->% 4*h),
	   expression(2*h %->% 4*h))
#install.packages("pheatmap")
library(pheatmap)
pdf("heatmap_dPRO_dRNA_alltranscript.pdf", width = 3.2, height = 3)
pheatmap(mat,
	cluster_rows = F,
	cluster_cols = F,
	labels_row = labels,
	labels_col = labels,
	breaks = br,
	color = col,
	main = expression(italic(Delta)*PRO-italic(Delta)*RNA~correlation))
dev.off()

```


#DEseq, bioreplicates correlation CPS-seq data.
```{R}
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
library(DESeq2)
cps.raw  <-read.table("~/Desktop/ReadcountTable/TEDseq/table/refCPSreadCount.txt",sep="\t",head=T)

cps.cor = cps.raw %>%
  filter_if(is.numeric, all_vars(. > 0)) 
head(cps.cor)
# Dummy DESeq to get normalized CPS-seq read counts
cps.rps = cps.cor %>%
  mutate(t_0 = rowSums(.[2:3]),
         t_1 = rowSums(.[4:5]),
         t_2 = rowSums(.[6:7]),
         t_4 = rowSums(.[8:9]),
         id = CPSid) %>%
  select(id, t_0, t_1, t_2, t_4)

cps.mat = cps.rps[-1]
cps.mat
rownames(cps.mat) = cps.rps$id
cpsInfo = data.frame(time = rep(c("early", "late"), each = 2),
                     row.names = colnames(cps.mat))

dds2 = DESeqDataSetFromMatrix(countData = cps.mat,
                              colData = cpsInfo,
                              design = ~ time)
dds2 = DESeq(dds2)
cps.cts = counts(dds2, norm = T)
cps.cts = data.frame(cps.cts)%>%
  mutate(id = rownames(cps.cts))%>%select(id, starts_with("t"))

cps.t0 = cps.cor %>%
  mutate(x = X0h.r1, y = X0h.r2)
cps.t1 = cps.cor %>%
  mutate(x = X1h.r1, y = X1h.r2)
cps.t2 = cps.cor %>%
  mutate(x = X2h.r1, y = X2h.r2)
cps.t4 = cps.cor %>%
  mutate(x = X4h.r1, y = X4h.r2)
```
