---
title: "Fig5E"
author: "Yeonui+Kwak"
date: "8/23/2020"
output: html_document
---




1.Set a working directory
```{R}
setwd("~/Desktop/Publication_Mar/Final_Fig5/Rcode/step4/")

```
#set up color
```{r}
library(RColorBrewer)
#nstall.packages("raster")
library(raster)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
yk.col = function(n = 5, sat = 0.7, lum = 1) {
	col = c("royalblue4", "deepskyblue3", "turquoise3",
	   "grey62", "goldenrod2", "orange2", "orangered2") %>%
	col2rgb %>%
	rgb2hsv
	return(colorRampPalette(hsv(col[1,], col[2,] * sat,
				    col[3,] * lum))(n)) }
```



#####
4.3 Temporal order(dPAL followed by dRNA.)
Regardless of transcriptional change, CDF plot for transcripts with dPAL(1->2)<0
Fig6C.general
```{R}
dpro.breaks <- seq(-5,5,1)
#sample
tmp=final%>%
  mutate(dPRO=PRO_2-PRO_1)%>%
  mutate("dCPS_1and2"=log2((CPS_2+1)/(CPS_1+1)))%>%
  mutate("dCPS_2and4"=log2((CPS_4+1)/(CPS_2+1)))%>%
  mutate("dTED_1and2"=TED_2-TED_1)%>%
  select(newid,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_1and2<=(-10),"PAL_DN",ifelse(dTED_1and2>=6,"PAL_UP",ifelse(abs(dTED_1and2)<5,"PAL_NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)#%>%
pdf("TNF_like.dTxn distribution.pdf",width=3,height=3.5)
ggplot(sample%>%filter(dTED_group!="PAL_NC"),aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(4)[1:4])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"TXN bins"))+ylim(c(-2.5,2.5))
dev.off()

sample2=sample%>%select(-dPRO_bin,-sum,-dPRO)%>%gather("dCPS_diff","dCPS_value",-newid,-dTED_1and2,-dTED_group)


sample2%>%group_by(dTED_group,dCPS_diff)%>%summarise(n())

```
5. Set CDF color
```{R}
col = yk.col(7)[c(2,5)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-1.5, 2.5) +
  ylab("Cumulative fraction")
```
6. Draw CDF plot for transcripts with decrease in PAL between 1h and 2h.
```{R}
pdf("F5E_TNFlikebehavior_PALdecrease.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_DN"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL decrease "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()

ks.test(sample2$dCPS_value[sample2$dTED_group=="PAL_DN"&sample2$dCPS_diff=="dCPS_1and2"],sample2$dCPS_value[sample2$dTED_group=="PAL_DN"&sample2$dCPS_diff=="dCPS_2and4"])

```

```{R}
sample=final%>%inner_join(sample2%>%select(newid,dTED_group),by="newid")%>%
  mutate(.PRO_0=(PRO_0-PRO_0))%>%
  mutate(.PRO_1=(PRO_1-PRO_0))%>%
  mutate(.PRO_2=(PRO_2-PRO_0))%>%
  mutate(.PRO_4=(PRO_4-PRO_2))%>%
  gather("time","txn",starts_with(".PRO_"))%>%
  #filter(abs(txn)<0.2)%>%
  separate("time",c("pro","prohour"),sep="_")%>%select(-pro)%>%mutate(prohour=as.numeric(prohour))

df_summary=sample%>%group_by(prohour,dTED_group)%>%summarise(n=n(),mean=mean(txn),sd=sd(txn),se = sd(txn, na.rm=T)/sqrt(sum(!is.na(txn))))
#df_summary$CI_lower <- df_summary$mean + qt((1-0.95)/2, df=df_summary$n-1)*df_summary$se
#df_summary$CI_upper <- df_summary$mean - qt((1-0.95)/2, df=df_summary$n-1)*df_summary$se
df_summary$CI_lower <- df_summary$mean + df_summary$sd
df_summary$CI_upper <- df_summary$mean - df_summary$sd

pdf("all TXN nc_PRO-seq_time-course0.4.pdf", width = 5, heigh=2.5)
ggplot(df_summary, aes(x=prohour, y=mean)) +
   geom_line(data=df_summary, aes(x=prohour, y=mean,group=dTED_group), size=1, alpha=0.8)+geom_ribbon(aes(ymin=CI_lower, ymax=CI_upper,group=dTED_group,fill=dTED_group), alpha=0.3)+scale_fill_manual(values=col)+theme_bw()+labs( title =expression("0h"%->%"4h"))+
  ylab("mean(Transcription)±sd")+ylim(c(-1.5,1.5))+xlab("hour")+labs(fill = expression(Delta*"RNA"))+facet_grid(.~dTED_group)+ scale_x_continuous(breaks=c(0,1,2,4))
dev.off()
```

```{R}
pdf("F5E_TNFlikebehavior_PALincrease.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_UP"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL increase "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()
ks.test(sample2$dCPS_value[sample2$dTED_group=="PAL_UP"&sample2$dCPS_diff=="dCPS_1and2"],sample2$dCPS_value[sample2$dTED_group=="PAL_UP"&sample2$dCPS_diff=="dCPS_2and4"])

```

```{R}
pdf("F6C_TNFlikebehavior_PALNC.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_NC"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL NC "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()
ks.test(sample2$dCPS_value[sample2$dTED_group=="PAL_NC"&sample2$dCPS_diff=="dCPS_1and2"],sample2$dCPS_value[sample2$dTED_group=="PAL_NC"&sample2$dCPS_diff=="dCPS_2and4"])

samp.test=sample2%>%filter(dTED_group=="PAL_DN")
samp.test=sample2%>%filter(dTED_group=="PAL_UP")
ks.test(samp.test$dCPS_value[samp.test$dCPS_diff=="dCPS_2and4"],samp.test$dCPS_value[samp.test$dCPS_diff=="dCPS_1and2"])
```
```{R}
col = yk.col(7)[c(2,4,6)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-1.5, 2.5) +
  ylab("Cumulative fraction")
pdf("F5E_TNFlikebehavior_all_CDF.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +facet_grid(dCPS_diff~.)+
  labs( title =expression("Transcripts with "*" PAL decrease "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA [3´-seq log2 FC]"))+labs(col=expression(italic(Delta)*"PAL"*" (1h"%->%"2h)"))+
  scale_color_manual(labels = c("DN","NC","UP"),values=col)
dev.off()
```
#No transcription change
```{R}
dpro.breaks <- seq(-0.5,0.5,0.1)
#sample
tmp=final%>%
  filter(abs(PRO_4-PRO_0)<0.5&abs(PRO_1-PRO_0)<0.5&abs(PRO_2-PRO_1)<0.5&abs(PRO_4-PRO_2)<0.5)%>%
  mutate(dPRO=PRO_2-PRO_1)%>%
  mutate("dCPS_1and2"=log2((CPS_2+1)/(CPS_1+1)))%>%
  mutate("dCPS_2and4"=log2((CPS_4+1)/(CPS_2+1)))%>%
  mutate("dTED_1and2"=TED_2-TED_1)%>%
  select(newid,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_1and2<=(-6),"PAL_DN",ifelse(dTED_1and2>=6,"PAL_UP",ifelse(abs(dTED_1and2)<3,"PAL_NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)#%>%
pdf("TxnNC.TNF_like.dTxn distribution.pdf",width=3,height=3.5)
ggplot(sample%>%filter(dTED_group!="PAL_NC"),aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(10)[1:10])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"TXN bins"))+ylim(c(-2.5,2.5))
dev.off()

sample2=sample%>%select(-dPRO_bin,-sum,-dPRO)%>%gather("dCPS_diff","dCPS_value",-newid,-dTED_1and2,-dTED_group)


sample2%>%group_by(dTED_group,dCPS_diff)%>%summarise(n())

```

5. Set CDF color
```{R}
col = yk.col(7)[c(2,5)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5, 2.5) +
  ylab("Cumulative fraction")
```
6. Draw CDF plot for transcripts with decrease in PAL between 1h and 2h.
```{R}
pdf("F6C_TXN.NC.TNFlikebehavior_PALdecrease.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_DN"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL decrease "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()

pdf("F6C_TXN.NC.TNFlikebehavior_PALincrease.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_UP"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL increase "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()

pdf("F6C_TXN.NC.TNFlikebehavior_PALNC.pdf",width=4.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample2%>%filter(dTED_group=="PAL_NC"),
            aes(x = dCPS_value,
                col = dCPS_diff),
            geom = "step") +
  labs( title =expression("Transcripts with "*" PAL NC "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"RNA abundance"))+
  scale_color_manual( 
                        labels = c(expression("1h" %->%"2h"), expression("2h" %->% "4h")),values=col)
dev.off()
samp.test=sample2%>%filter(dTED_group=="PAL_DN")
samp.test=sample2%>%filter(dTED_group=="PAL_NC")
ks.test(samp.test$dCPS_value[samp.test$dCPS_diff=="dCPS_2and4"],samp.test$dCPS_value[samp.test$dCPS_diff=="dCPS_1and2"])
samp.test
```

```{R}
col = yk.col(7)[c(2,4,6)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-1.5, 2.5) +
  ylab("Cumulative fraction")
pdf("F5E_Txn NC_TNFlikebehavior_all_CDF.pdf",width=4.5,height=3)
cdf_common +
  stat_ecdf(data = sample2,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +facet_grid(dCPS_diff~.)+
  labs( title =expression("Transcripts with "*" PAL decrease "*("1h"%->%"2h"))) +
  xlab(expression(italic(Delta)*"RNA [3´-seq log2 FC]"))+labs(col=expression(italic(Delta)*"PAL"*" (1h"%->%"2h)"))+
  scale_color_manual(labels = c("DN","NC","UP"),values=col)
dev.off()
```

```{R}
sample=final%>%inner_join(sample2%>%select(newid,dTED_group),by="newid")%>%
  mutate(.PRO_0=(PRO_0-PRO_0))%>%
  mutate(.PRO_1=(PRO_1-PRO_0))%>%
  mutate(.PRO_2=(PRO_2-PRO_0))%>%
  mutate(.PRO_4=(PRO_4-PRO_2))%>%
  gather("time","txn",starts_with(".PRO_"))%>%
  #filter(abs(txn)<0.2)%>%
  separate("time",c("pro","prohour"),sep="_")%>%select(-pro)%>%mutate(prohour=as.numeric(prohour))

df_summary=sample%>%group_by(prohour,dTED_group)%>%summarise(n=n(),mean=mean(txn),sd=sd(txn),se = sd(txn, na.rm=T)/sqrt(sum(!is.na(txn))))
#df_summary$CI_lower <- df_summary$mean + qt((1-0.95)/2, df=df_summary$n-1)*df_summary$se
#df_summary$CI_upper <- df_summary$mean - qt((1-0.95)/2, df=df_summary$n-1)*df_summary$se
df_summary$CI_lower <- df_summary$mean + df_summary$sd
df_summary$CI_upper <- df_summary$mean - df_summary$sd

pdf("all TXN nc_PRO-seq_time-course0.4.pdf", width = 5, heigh=2.5)
ggplot(df_summary, aes(x=prohour, y=mean)) +
   geom_line(data=df_summary, aes(x=prohour, y=mean,group=dTED_group), size=1, alpha=0.8)+geom_ribbon(aes(ymin=CI_lower, ymax=CI_upper,group=dTED_group,fill=dTED_group), alpha=0.3)+scale_fill_manual(values=col)+theme_bw()+labs( title =expression("0h"%->%"4h"))+
  ylab("mean(Transcription)±sd")+ylim(c(-1.5,1.5))+xlab("hour")+labs(fill = expression(Delta*"RNA"))+facet_grid(.~dTED_group)+ scale_x_continuous(breaks=c(0,1,2,4))
dev.off()



```