---
title: "Fig5B_dRNA-dPAL"
author: "Yeonui+Kwak"
date: "8/23/2020"
output: html_document
---



1.Set a working directory
```{R}
setwd("~/Desktop/Publication_Mar/Final_Fig5/Rcode/step2/")

```
#set up color
```{r}
library(RColorBrewer)
#nstall.packages("raster")
library(raster)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
yk.col = function(n = 5, sat = 0.7, lum = 1) {
	col = c("royalblue4", "deepskyblue3", "turquoise3",
	   "grey62", "goldenrod2", "orange2", "orangered2") %>%
	col2rgb %>%
	rgb2hsv
	return(colorRampPalette(hsv(col[1,], col[2,] * sat,
				    col[3,] * lum))(n)) }
```


3. Load data


```{R}
final<-read.table("PRO_TED_CPS.readcounttable.txt",sep="\t",header=T,stringsAsFactors = F)
head(final)
final%>%filter(hgnc=="TNF")
```



Data manipulation:Group by dPAL
0.1
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)

sampln_=final%>%
  mutate(dPRO=PRO_1-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_1+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_1-TED_0)%>%
  select(hgnc,newid,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")%>%
  #mutate("dTED_group"=ifelse(dTED_0and4<=(-10),"PAL_DN",ifelse(dTED_0and4>=10,"PAL_UP","PAL_NC")))%>%
  #mutate("dCPS_group"=ifelse(dCPS_value<quantile(dCPS_value,0.3),"DN",ifelse(dCPS_value>quantile(dCPS_value,0.7),"UP","NC")))%>%
   #binning
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))
  ungroup()%>%select(sum,dPRO_bin)

nested_sample=final%>%ungroup()%>%
  mutate(dPRO=PRO_1-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_1+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_1-TED_0)%>%
  select(newid,hgnc,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")%>%
  #mutate("dCPS_group"=ifelse(dCPS_value<quantile(dCPS_value,0.3),"DN",ifelse(dCPS_value>quantile(dCPS_value,0.3),"UP","NC")))%>%
   #binning
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample01=sample
sample01%>%group_by(dCPS_group)%>%summarise(n())
ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F5B inset_General_0h-1h.dTXN distribution.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.001)+scale_colour_manual(name=expression(Delta*"TXN"),values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN [PRO-seq log2 FC (1h/0h)]"))+labs(title=expression("0h"%->%"1h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-20,20) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:dRNA_0.1pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +
  labs( title =expression("0h"%->%"1h")) +
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```

Data manipulation:Group by dPAL
0 VS 2
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_2-TED_0)%>%
  select(hgnc,newid,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample02=sample
sample02%>%group_by(dCPS_group)%>%summarise(n())
ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.0.2.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("0h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:dRNA_0.2pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +
  labs( title =expression("0h"%->%"2h")) +
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```


0 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_4-TED_0)%>%
  select(newid,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample04=sample
sample04%>%group_by(dCPS_group)%>%summarise(n())

ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F5B_General.0h-4h.dTXN distribution.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.001)+scale_colour_manual(name=expression(Delta*"TXN"),values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN [PRO-seq log2 FC(4h/0h)]"))+labs(title=expression("0h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F5B_0h-4h_CDFplot2.pdf",width=5,height=3)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +scale_color_manual(name=expression(Delta*"RNA"),values=col)+
  labs( title =expression("0h"%->%"4h")) +xlim(c(-30,30))+
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```

1 vs 2
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_2-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample12=sample

ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.1.2.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:dRNA_1.2pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +
  labs( title =expression("1h"%->%"2h")) +
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```
1 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_4-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample14=sample

ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.1.4.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:dRNA_1.4pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +
  labs( title =expression("1h"%->%"4h")) +
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```

2 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_2)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_2+1)))%>%
  mutate("dTED_value"=TED_4-TED_2)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dCPS_group"=ifelse(dCPS_value<(-1),"DN",ifelse(dCPS_value>1,"UP",ifelse(abs(dCPS_value)<0.5,"NC","NA"))))%>%filter(dCPS_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dCPS_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dCPS_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample24=sample

ks.test(sample$dTED_value[sample$dCPS_group=="UP"],sample$dTED_value[sample$dCPS_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.2.4.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dCPS_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("2h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"RNA"))
dev.off()
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:dRNA_2.4pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dTED_value,
                col = dCPS_group),
            geom = "step") +
  labs( title =expression("2h"%->%"4h")) +
  xlab(expression(italic(Delta)*"PAL"))+labs(col=expression(italic(Delta)*"RNA"))#+
dev.off()
```



#x axis: dRNA
0.1
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_1-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_1+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_1-TED_0)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-6),"DN",ifelse(dTED_value>6,"UP",ifelse(abs(dTED_value)<3,"NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample01=sample

ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.0.1.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("0h"%->%"1h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5,2.5) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:0.1pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("0h"%->%"1h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```
0vs2
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_2-TED_0)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-6),"DN",ifelse(dTED_value>6,"UP",ifelse(abs(dTED_value)<3,"NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample02=sample
sample02%>%group_by(dTED_group)%>%summarise(n())
ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.0.2.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("0h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5,2.5) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:0.2pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("0h"%->%"2h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```
0 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_4-TED_0)%>%
  select(newid,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<3,"NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample04=sample
sample04%>%group_by(dTED_group)%>%summarise(n())
ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.0.4.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.5)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("0h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(c(-4,4)) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:0.4pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("0h"%->%"4h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```


1vs 2
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_2-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample12=sample

ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.1.2.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"2h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5,2.5) +
  ylab("Cumulative fraction")
```


6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:1.2pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("1h"%->%"2h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```



1 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_4-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample14=sample

ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.1.4.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("1h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5,2.5) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:1.4pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("1h"%->%"4h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```











2 vs 4
```{R}

# set up cut-off values 
dpro.breaks <- seq(-5,5,1)
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_2)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_2+1)))%>%
  mutate("dTED_value"=TED_4-TED_2)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")

sampln_=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%summarise(sum=n())%>%ungroup()%>%
  complete(dTED_group,nesting(dPRO_bin),fill =list(sum=0))%>%group_by(dPRO_bin)%>%summarise(sum=min(sum))

nested_sample=tmp%>%
  mutate(dPRO_bin=cut(dPRO,breaks=dpro.breaks))%>%
  group_by(dTED_group,dPRO_bin)%>%
  nest()%>%
  ungroup()%>%
  inner_join(sampln_,by="dPRO_bin")%>%ungroup()

sampled<-nested_sample%>%
  mutate(samp=map2(data,sum,sample_n))

sample=sampled%>%select(-data)%>%unnest(samp)
sample24=sample

ks.test(sample$dCPS_value[sample$dTED_group=="UP"],sample$dCPS_value[sample$dTED_group=="DN"])
```

#Distribution of dTxn among TED-group
```{R}
pdf("F6_General.dTXN distribution.dTEDgroup.2.4.pdf",width=3.5,height=3)
ggplot(sample,aes(x=dTED_group,y=dPRO,col=dPRO_bin))+geom_quasirandom(size=0.2)+scale_colour_manual(values=yk.col(7)[1:7])+ylab(expression(italic(Delta)*"TXN (PRO-seq log2 FC)"))+labs(title=expression("2h"%->%"4h"))+theme_bw()+xlab(expression(italic(Delta)*"PAL"))
dev.off()
```
5. Set CDF color (N=3)
```{R}
col = yk.col(9)[c(2,5,8)] 
cdf_common = ggplot() +
  scale_color_manual(values = col) +
  theme_bw() +
  xlim(-2.5,2.5) +
  ylab("Cumulative fraction")
```

6. Draw CDF plot for transcripts : dPAL and dRNA association between 0h and 1h.
```{R}
pdf("F6_General_xaxis:2.4pdf",width=3.5,height=2.5)
cdf_common +
  stat_ecdf(data = sample,
            aes(x = dCPS_value,
                col = dTED_group),
            geom = "step") +
  labs( title =expression("2h"%->%"4h")) +
  xlab(expression(italic(Delta)*"RNA"))+labs(col=expression(italic(Delta)*"PAL"))#+
dev.off()
```
#General. Save PAL increase gene id vs decrease and no change gene ids
#Withoutsampling
```{R}
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_1-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_1+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_1-TED_0)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample01=tmp
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_2-TED_0)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample02=tmp
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_0)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_0+1)))%>%
  mutate("dTED_value"=TED_4-TED_0)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample04=tmp
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_2-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_2+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_2-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample12=tmp
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_1)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_1+1)))%>%
  mutate("dTED_value"=TED_4-TED_1)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample14=tmp
tmp=final%>%ungroup()%>%
  mutate(dPRO=PRO_4-PRO_2)%>%
  mutate("dCPS_value"=log2((CPS_4+1)/(CPS_2+1)))%>%
  mutate("dTED_value"=TED_4-TED_2)%>%
  select(newid,newid_old,starts_with("d"))%>%
  mutate("dTED_group"=ifelse(dTED_value<(-10),"DN",ifelse(dTED_value>10,"UP",ifelse(abs(dTED_value)<5,"NC","NA"))))%>%filter(dTED_group!="NA")
sample24=tmp

write.table(sample01,"0.1h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample02,"0.2h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample04,"0.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample12,"1.2h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample14,"1.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample24,"2.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)

```



#General. Save PAL increase gene id vs decrease and no change gene ids

```{R}

write.table(sample01,"sampled_0.1h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample02,"sampled_0.2h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample04,"sampled_0.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample12,"sampled_1.2h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample14,"sampled_1.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)
write.table(sample24,"sampled_2.4h.PALchange.txt",sep="\t",col.names = T,row.names = F,quote=F)

```



